### PR TITLE
fix(wording): Implement epicene writing

### PR DESCRIPTION
**Pull request by ZoeThivet**
**Problem**
I noticed some issues in the wording (typos and non-epicene writing)

**Solution**
I fixed some of the problems (didn't read all the file... for now :) )

### CODE REVIEW

**Comment by frankrousseau** [comment]
Thank you Zoe for your contribution. 
But the best to modify the translations is to use POEditor: https://poeditor.com/projects/view?id=367985
Do you think you can apply your modifications via this platform?

**Comment by ZoeThivet** [comment]
@frankrousseau Sure, but I don't think I'm allowed to do it (I signed in with my Github account)

image

**Comment by ZoeThivet** [comment]
@frankrousseau how shall I proceed please?

**Comment by frankrousseau** [comment]
Sorry for the late feedback. I think I gave you the wrong link. Here is the good one: https://poeditor.com/join/project?hash=fpUejpWDVo

**Pull request closed without merging**
