### PR TITLE
Edits section

### PR DESCRIPTION
**Pull request by ex5**
Front-end part of https://github.com/cgwire/kitsu/discussions/801

Requires https://github.com/cgwire/zou/pull/413

### CODE REVIEW

**Comment by frankrousseau** [comment]
Hello @ex5,

First and foremost thank you for this new feature addition. I think you forgot to add the possibility to add Edit task type. Currently it's only possible to add shot task type or asset task types. Can you change this?

**Comment by ex5** [comment]
> I think you forgot to add the possibility to add Edit task type. Currently it's only possible to add shot task type or asset task types.

Just to clarify, adding in what context do you mean? In `Create Production` page or somewhere else?

I've `Create Production` wizard as is, but I can probably try and add another step there for Edits, yes.

**Comment by ex5** [comment]
Ah, right, this:

2022-02-04-162520_3440x1440_scrot_

Yep, will update the PR, if not today, then next week Tuesday.

**Comment by frankrousseau** [comment]
Ok great thank you

**Comment by ex5** [comment]
@frankrousseau I've added changes to the Task Type admin section:


https://user-images.githubusercontent.com/176934/152828639-c2c00758-7e8a-40de-b7b6-5e1f2bc67b79.mp4



I've got a question concerning some of the changes in this PR, however.

There are a lot of checks that use `TaskType.for_shots` flag in the code (both here, and in Zou, I think), which I've had to modify to support Edits task types: it's no longer a choice of 2 that can be handled with a boolean flag. See, for example, [here](https://github.com/cgwire/kitsu/pull/804/files#diff-9534553837b92cd14c33d1fa5716f138971da04f96320dc8b46658555ef85440R43).

So, the question is: is it safe to just check `TaskType.for_entity` everywhere instead? If it is, I'll update the patch accordingly.
Or is there a specific reason `TaskType.for_shots` flag is used that should be taken into account?

**Comment by frankrousseau** [comment]
No, we should remove the `for_shots` flag. I used it for performance reasons. But in the end, I don't think it improves anything. Plus, it doesn't fit with the idea of widening the available entities.

If you can get rid of it, it would help!

**Comment by ex5** [comment]
I've updated the patch, replacing `for_shots` usage with `for_entity`.
Currently, playlists appear to be broken on this branch, I'm trying to figure out how to fix them.

**Comment by ex5** [comment]
Actually, not sure if playlists are broken due to the patch, I get the same error on `master`, but on both `master` and this branch the playlists are created anyway, and can be viewed, annotated and so on.

The error is this, in case maybe it looks familiar, because I'm having hard times figuring out whats causing it:

```
Uncaught TypeError: _ref2 is undefined
    loadPlaylists [playlists.js:61](webpack:///src/store/modules/playlists.js?fd79)
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    mappedAction vuex.esm.js:1064
    callback ViewPlaylistModal.vue:201
    editPlaylist playlists.js:141
    put client.js:30
    callback client.js:647
    Request client.js:467
    emit index.js:145
    onreadystatechange client.js:763
    _end client.js:737
    end client.js:713
    put client.js:25
    updatePlaylist playlists.js:70
    editPlaylist playlists.js:138
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    mappedAction vuex.esm.js:1064
    savePlaylist ViewPlaylistModal.vue:192
    promise callback*savePlaylist ViewPlaylistModal.vue:183
    VueJS 4
    runConfirmation EditPlaylistModal.vue:168
    VueJS 4
    click ModalFooter.vue:18
    VueJS 33
playlists.js:61
    loadPlaylists playlists.js:61
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    mappedAction vuex.esm.js:1064
    mappedAction self-hosted:1178
    callback ViewPlaylistModal.vue:201
    editPlaylist playlists.js:141
    put client.js:30
    callback client.js:647
    Request client.js:467
    emit index.js:145
    onreadystatechange client.js:763
    (Async: EventHandlerNonNull)
    _end client.js:737
    end client.js:713
    put client.js:25
    updatePlaylist playlists.js:70
    editPlaylist playlists.js:138
    wrappedActionHandler vuex.esm.js:851
    dispatch vuex.esm.js:516
    boundDispatch vuex.esm.js:406
    mappedAction vuex.esm.js:1064
    mappedAction self-hosted:1178
    savePlaylist ViewPlaylistModal.vue:192
    (Async: promise callback)
    savePlaylist ViewPlaylistModal.vue:183
    savePlaylist self-hosted:1178
    VueJS 4
    runConfirmation EditPlaylistModal.vue:168
    runConfirmation self-hosted:1178
    VueJS 4
    click ModalFooter.vue:18
    VueJS 33
```

**Comment by frankrousseau** [comment]
I close the PR, the code was integrated. But I don't know why it didn't mark this PR as merged.

**Comment by ex5** [comment]
Thank you @frankrousseau !
(I think GitHub only marks PRs merged when the merge commit was made from its UI, or at least it used to be like this)

**Pull request closed without merging**
