### PR TITLE
Fix: quota day display when the day date is 1 digit

### PR DESCRIPTION
**Pull request by GoOz**
fix: #403

**Problem**
When displaying quotas by day, quotas in the first 9 days didn't display because it was 1 digit for the day date when the data sent was 2 digits for the day date, so it didn't match.

**Solution**
Enforcing date format of 2 digits for days as well.

### CODE REVIEW

**Comment by frankrousseau** [comment]
Great thank you!

**Comment by frankrousseau** [comment]
Can you add tests for this?

**Comment by GoOz** [comment]
> Can you add tests for this?

For the whole page or just for the method ?

**Comment by frankrousseau** [comment]
For this method

**Comment by frankrousseau** [comment]
Thx!

**Pull request merged**
